pipeline{
    agent any
    stages {
        stage('Clean Up'){
            steps{
                deleteDir()
            }
        }
        stage('Clone Repo'){
            steps{
                sh "git clone https://github.com/reymachain/jreyesmachain.git"
            }
        }
        stage('Build'){
            steps{
                dir("jreyesmachain"){
                    sh "mvn clean install"
                }
            }
            
        }
        stage('Test'){
            steps{
                dir("jreyesmachain"){
                    sh "mvn test"
                }
            }
        }
        stage('Complete'){
            steps{
                echo "Job Completed for bug fixing"
            }
        }
    }

}
